class Intents {
    constructor(){
    }

    static intents(){
        return {

            OTHERS:'OTHERS',
            TICKET_LIST:'TICKET_LIST',
            ACTION_LIST: 'ACTION_LIST',
            SR_LIST: 'SR_LIST',
            IT_LOGIN_LIST: 'IT_LOGIN_LIST',
            IT_CLEAN_LIST : 'IT_CLEAN_LIST',
            IT_SECURITY_LIST:"IT_SECURITY_LIST",
            IT_NETWORK_LIST: 'IT_NETWORK_LIST',
            IT_SETTING_LIST: 'IT_SETTING_LIST',
            IT_TROUBLESHOOT: 'IT_TROUBLESHOOT',
            IT_ANTIVIRUS_LIST:'IT_ANTIVIRUS_LIST',
            BOT_INITIALIZE_ACTION : 'BOT_INITIALIZE - action',
            BOT_INITIALIZE_FAQ : 'BOT_INITIALIZE - faq',
            BOT_INITIALIZE_TROUBLESHOOT : 'BOT_INITIALIZE - troubleshoot',
            IT_INITIALIZE_ACTION : 'IT_INITIALIZE_ACTION',
            IT_INITIALIZE_FAQ : 'IT_INITIALIZE_FAQ',
            IT_INITIALIZE_TROUBLESHOOT : 'IT_INITIALIZE_TROUBLESHOOT',
            IT_ACTION_INITIALIZER : 'IT_ACTION_INITIALIZER',
            IT_ACTION_COMPONENT : 'IT_ACTION_COMPONENT',
            IT_ISSUE_COMPONENT : 'IT_ISSUE_COMPONENT',
            IT_SECURITY_COMPONENT : 'IT_SECURITY_COMPONENT',
            IT_SR_COMPONENT : 'IT_SR_COMPONENT',
            IT_NETWORK_COMPONENT : 'IT_NETWORK_COMPONENT',
            IT_LOGIN_COMPONENT : 'IT_LOGIN_COMPONENT',
            IT_ANTIVIRUS_COMPONENT : 'IT_ANTIVIRUS_COMPONENT',
            IT_SETTING_COMPONENT : 'IT_SETTING_COMPONENT',
            IT_CONVO_CONFIRMATION :'IT_CONVO_CONFIRMATION',
            IT_CONVO:'IT_CONVO',
            resume_upload:'resume_upload',
            job_org:'job_org',
            job_subcategories:'job_subcategories',
            experience:'experience',
            video:'video',
            opportunity:'opportunity',
            loss_one : 'loss_one',
            account_name : 'account_name',
            emailaddress1 : 'emailaddress1',
            websiteurl : 'websiteurl',
            select_option_first : 'select_option_first',
            no_output :'no_output',
            open_option :'open_option',
            firstname_update : 'firstname_update',
            click_totalamount :'click_totalamount',
            lastname_change : 'lastname_change',
            PROFILE:'PROFILE',
            Application_login:'Application_login',
            EMAIL:'EMAIL',
            IT_TROUBLESHOOT_COMPONENT : 'IT_TROUBLESHOOT_COMPONENT',
            IT_ACTION_APPROVAL : 'IT_ACTION_APPROVAL',
            IT_CLEAN_CONFIRMATION : 'IT_CLEAN_CONFIRMATION',
            IT_ACTION_CONFIRMATION : 'IT_ACTION_CONFIRMATION',
            IT_SR_CONFIRMATION : 'IT_SR_CONFIRMATION',
            IT_LOGIN_CONFIRMATION : 'IT_LOGIN_CONFIRMATION',
            IT_SETTING_CONFIRMATION : 'IT_SETTING_CONFIRMATION',
            IT_TROUBLESHOOT_CONFIRMATION : 'IT_TROUBLESHOOT_CONFIRMATION',
            IT_NETWORK_CONFIRMATION : 'IT_NETWORK_CONFIRMATION',
            IT_SECURITY_CONFIRMATION : 'IT_SECURITY_CONFIRMATION',
            IT_ANTIVIRUS_CONFIRMATION : 'IT_ANTIVIRUS_CONFIRMATION',
            IT_ACTION_EXECUTE : 'IT_ACTION_EXECUTE',
            IT_TICKET_CAPTURE : 'IT_TICKET_CAPTURE',
            IT_TICKET_LOG: 'IT_TICKET_LOG',
            Intent_welcome:'welcome',
            IT_Options:'IT_Options',
            resetadpassword:'resetadpassword',
            IT_TICKET_LOG_CATEGORY : 'IT_TICKET_LOG_CATEGORY',
            IT_TICKET_LOG_SUBCATEGORY : 'IT_TICKET_LOG_SUBCATEGORY',
            IT_TROUBLESHOOT_INITIALIZER : 'IT_TROUBLESHOOT_INITIALIZER',
            IT_TROUBLESHOOT_CONFIRMATION : 'IT_TROUBLESHOOT_CONFIRMATION',
            IT_TROUBLESHOOT_EXECUTE :'IT_TROUBLESHOOT_EXECUTE',
            BOT_FALLBACK_YES :'BOT_FALLBACK - yes',
            IT_SUPPORT_EXTENSION : 'IT_SUPPORT_EXTENSION',
            IT_SUPPORT_PERSON : 'IT_SUPPORT_PERSON',
            IT_TICKET_STATUS : 'IT_TICKET_STATUS',
            Host_operation: 'Host_operation',
            email_otp: 'email_otp',
            email_otp2: 'email_otp2',
            hostgroupdetail_id: 'hostgroupdetail_id',
            hostgroupdetails: 'hostgroupdetails',
            Performance_issue: 'Performance_issue',
            hostgroupseltask: 'hostgroupseltask',
            hostgroup_name: 'hostgroup_name',
            Hostgroup_name: 'Hostgroup_name',
            deletionhostgroup_name: 'deletionhostgroup_name',
            hostgroup_deletion: 'hostgroup_deletion',
            useraction: 'useraction',
            actiontask: 'actiontask',
            useractiondisable: 'useractiondisable',
            disableactionintent: 'disableactionintent',
            enablehostname: 'enablehostname',
            enabledisablegroup:'enabledisablegroup',
            enabledisabletask: 'enabledisabletask',
            disablehostname: 'disablehostname',
            activeusersname: 'activeusersname',
            enablemedianame: 'enablemedianame',
            mediatypedisable: 'mediatypedisable',
            urlname: 'urlname',
            statuscodename: 'statuscodename',
            webusername: 'webusername',
            eventduration: 'eventduration',
            reportgentask: 'reportgentask',
            Mediatask: 'Mediatask',
            mediatype: 'mediatype',
            installations_yes:'installations_yes',
            login_component_yes:'login_component_yes',
            system_performance_issue:'system_performance_issue',
            browser_performance_issue:'browser_performance_issue',
            system_issue_yes:'system_issue_yes',
            network_issue:'network_issue',
            network_issue_yes:'network_issue_yes',
            outlook_issue_yes:'outlook_issue_yes',
            browser_settings_yes:'browser_settings_yes',
            zabbixactioname_yes:'zabbixactioname_yes',
            zabbixactioname:'zabbixactioname',
            zabbixactionlist:'zabbixactionlist',
            enabledisablehostask:'enabledisablehostask',
            enabledisablenamegroup:'enabledisablenamegroup',
            uninstallation_issue:'uninstallation_issue',
            installation_issue:'installation_issue',
            uninstallations_yes:'uninstallations_yes',
            browser_issue_yes:'browser_issue_yes',
            component_action:'component_action',
            raise_ticket:'raise_ticket',
            get_user_info:'get_user_info',
            component_confirmation:'component_confirmation',
            get_ticket_id: 'get_ticket_id',
            update_ticket: 'update_ticket',
            hmshostname: 'hmshostname',
            UIPath : 'UIPath',
            ui_process : 'ui_process',
            process_status : 'process_status',
            MDM: 'MDM',
            ios: 'ios',
            end_point_verification:'end_point_verification',
            google_authenticator_configuration:'google_authenticator_configuration',
            install_or_uninstall_software_from_self_service:'install_or_uninstall_software_from_self_service',
            prevent_issue:'prevent_issue',
            ticket_creation:'ticket_creation',
            vpn_configuration:'vpn_configuration',
            android: 'android',
            search:"search",
            install_project_software:'install_project_software',
            install_standard_software:'install_standard_software',
            login_component:'login_component',
            uninstall_software_A_to_E:'uninstall_software_A_to_E',
            uninstall_software_F_to_J:'uninstall_software_F_to_J',
            uninstall_software_K_to_O:'uninstall_software_K_to_O',
            uninstall_software_P_to_T:'uninstall_software_P_to_T',
            uninstall_software_U_to_Z:'uninstall_software_U_to_Z',
            install_project_software_A_to_E:'install_project_software_A_to_E',
            install_project_software_F_to_J:'install_project_software_F_to_J',
            install_project_software_K_to_O:'install_project_software_K_to_O',
            install_project_software_P_to_T:'install_project_software_P_to_T',
            install_project_software_U_to_Z:'install_project_software_U_to_Z',
            install_standard_software_A_to_E:'install_standard_software_A_to_E',
            install_standard_software_F_to_J:'install_standard_software_F_to_J',
            install_standard_software_K_to_O:'install_standard_software_K_to_O',
            install_standard_software_P_to_T:'install_standard_software_P_to_T',
            install_standard_software_U_to_Z:'install_standard_software_U_to_Z'



        };
    }

    static events(){
        return {
            bot_initialize_event : 'bot_initialize_event',
            it_action_initializer_event : 'it_action_initializer_event',
            it_action_component_event  : 'it_action_component_event',
            it_action_approval_event : 'it_action_approval_event',
            it_action_confirmation_event : 'it_action_confirmation_event',
            it_ticket_log_event : 'it_ticket_log_event',
            it_ticket_log_category_event : 'it_ticket_log_category_event',
            it_ticket_log_subcategory_event : 'it_ticket_log_subcategory_event',
            it_troubleshoot_initializer_event : 'it_troubleshoot_initializer_event',
            it_troubleshoot_confirmation_event:'it_troubleshoot_confirmation_event'
        };
    }
}

module.exports = Intents;